Repository proteiin/nb04-seven-team1, pull requests merged in 2025-08, with the labels that each got.

#5 Feature/model: change model format
  .gitignore
  main.js
  prisma/schema.prisma
  src/controller/.gitkeep
  src/repository/.gitkeep
  src/router/.gitkeep
  src/service/.gitkeep
Labels: db

#12 feat(api): add API endpoint "/tags"
  main.js
  src/controller/tag-controller.js
  src/repository/tag-repository.js
  src/router/tag-router.js
  src/service/tag-service.js
Labels: api

#11 feat(api): add API endpoint "/groups" (modifying)
  .gitignore
  main.js
  prisma/schema.prisma
  src/controller/group-controller.js
  src/middleware/group-middleware.js
  src/repository/group-repository.js
  src/repository/group-tag-repository.js
  src/router/group-router.js
  src/service/group-service.js
Labels: api

#29 feat(api): Separate all groups of users into owners and participants
  src/service/user-service.js
Labels: api

#50 fix: change file limit 5 to 3
  src/router/image-router.js
Labels: bug, api
